### ISSUE TITLE
Does this package support column-level mapping?

### ISSUE THREAD

**Issue by mattzeunert** [mozilla/pretty-fast#25]
I just tried this and it seems the column is always 0. Is it correct that this package doesn't support column-level mapping? If so, I can do a PR to add that info to the readme.

Here's my code, in case it should be working:

```
var uglyJS = "function ugly(){a + code()}";
var frameObject = {
  columnNumber: uglyJS.indexOf("code()"),
  lineNumber: 1
};
prettifyAndSourceMap(uglyJS, frameObject);

function prettifyAndSourceMap(code, frameObject) {
  var pretty = prettyFast(code, {
    indent: "  ",
    url: "meaningless.js"
  });
  var sm = pretty.map.toString();

  var consumer = new sourceMap.SourceMapConsumer(sm);

  console.log(
    consumer.generatedPositionFor({
      source: "meaningless.js",
      line: frameObject.lineNumber,
      column: frameObject.columnNumber
    })
  );

  console.log(pretty.code);
}

// Output:
{ line: 2, column: 0, lastColumn: null }
// Would expect column to be 6

function ugly() {
  a + code()
}
```

**Comment by jasonLaster** [comment]
Hey @mattzeunert yep - you should get a good map out. let me share where we do it in the debugger
https://github.com/devtools-html/debugger.html/blob/master/src/actions/sources/prettyPrint.js#L40-L44

stop by our slack or ping me on twitter :)
https://devtools-html-slack.herokuapp.com/

**Comment by mattzeunert** [comment]
Thanks Jason!

I just took a look at the code, and it there's [only one mapping per line](https://github.com/mozilla/pretty-fast/blob/cea1dee342d7555d0cb7d0c0e6bc412f29bc60b2/pretty-fast.js#L699).

```
     * We buffer our writes so that we only create one mapping for each line in
     * the source map. This enhances performance by avoiding extraneous mapping
     * serialization, and flattening the tree that
     * `SourceNode#toStringWithSourceMap` will have to recursively walk. When
     * timing how long it takes to pretty print jQuery, this optimization
     * brought the time down from ~390 ms to ~190ms!
```

I don't need column-level mapping right now, but in case anyone else runs into this, it's easy to remove the per-line buffering logic:

```
return function write(str, line, column) {
  result.add(new SourceNode(line, column, options.url, str));
};
```

**Comment by mattzeunert** [comment]
I think this would be nice to have. Can I add an option like `columnLevelAccurancy: true`?
