### ISSUE TITLE
Template literals break pretty print

### ISSUE THREAD

**Issue by Loirooriol** [mozilla/pretty-fast#26]
From https://github.com/devtools-html/debugger.html/issues/5495.

Store this script in a file:

```js
`${1}${2}${3}`;
function func() {
  for (let bar of foo) {
    for (let baz of bar) {
      baz();
    }
  }
}
```

Run it in a HTML page. Open the debugger, locate the script, and click "Pretty print source".

Result: horrible invalid syntax

![screenshot](https://user-images.githubusercontent.com/7477678/36505206-0d6b19d8-1753-11e8-84b3-05d8a6c25f66.png)

**Comment by nchevobbe** [comment]
Checked on Firefox 109, on https://ffx-devtools-pretty-print-template-literals.glitch.me/ `script.js` gets prettified into:

```js
`${ 1 }${ 2 }${ 3 }`;
function func() {
  for (let bar of foo) {
    for (let baz of bar) {
      baz();
    }
  }
}
```

which looks good to me.
It was probably fixed in https://github.com/mozilla/pretty-fast/pull/31
