### ISSUE TITLE
JavaScript Style

### ISSUE THREAD

**Issue by Nerixyz** [mozilla/pretty-fast#32]
While reading the code, I wondered why the project uses this old style JavaScript despite running in Firefox with a "modern" JS implementation. 
I tried updating ESLint and the JS-Style on a fork and it works fine.
So is this a clear decision to use the old style or was the new style never considered?

**Comment by nchevobbe** [comment]
Not sure what what you mean by "old style"
Can you point to some code?

**Comment by Nerixyz** [comment]
I suppose, I was referring to the use of `var` over `let` and `function () { }` declarations over lambdas. I don't really mind it.
