### ISSUE TITLE
breaks for ... of statement by removing whitespace

### ISSUE THREAD

**Issue by gh89275** [mozilla/pretty-fast#41]
for (let x of y) ;
becomes

    for (let xofy);

(tested in current Firefox debugger pretty-print feature; I don't know if it's fixed in pretty-fast, but [a comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1206633#c3) on the [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1206633) suggests the issue goes upstream to here)

**Comment by Nerixyz** [comment]
This is already fixed ([commit](https://github.com/mozilla/pretty-fast/commit/51e0f8873315acff4022cc4db2c659226fd8caaf), [test](https://github.com/mozilla/pretty-fast/blob/master/test.js#L297), [snap](https://github.com/mozilla/pretty-fast/blob/master/__snapshots__/test.js.snap#L110)), however the version on npm is out of date and thus is the version used in firefox.

**Comment by nchevobbe** [comment]
verified as fixed in Firefox
